# Generated by Django 3.1.1 on 2022-02-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades y estados'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='descripcion',
            field=models.CharField(help_text='Ciudades y estados', max_length=100, unique=True),
        ),
    ]
